/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyekkami;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASPIRE V5
 */
public class masukanBahan extends javax.swing.JFrame {

    /**
     * Creates new form masukanBahan
     */
    public masukanBahan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bahan1textfield = new javax.swing.JTextField();
        bahan2textfield = new javax.swing.JTextField();
        bahan3textfield = new javax.swing.JTextField();
        tampilkanButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tampilTextArea = new javax.swing.JTextArea();
        nextButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("MASUKKAN BAHAN-BAHAN YANG ADA:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 30, 440, 21);
        getContentPane().add(bahan1textfield);
        bahan1textfield.setBounds(30, 70, 210, 40);

        bahan2textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bahan2textfieldActionPerformed(evt);
            }
        });
        getContentPane().add(bahan2textfield);
        bahan2textfield.setBounds(30, 120, 210, 40);
        getContentPane().add(bahan3textfield);
        bahan3textfield.setBounds(30, 170, 210, 40);

        tampilkanButton.setText("TAMPILKAN RESEP");
        tampilkanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tampilkanButton);
        tampilkanButton.setBounds(290, 80, 170, 50);

        tampilTextArea.setColumns(20);
        tampilTextArea.setRows(5);
        jScrollPane2.setViewportView(tampilTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(16, 230, 350, 140);

        nextButton.setText("NEXT");
        getContentPane().add(nextButton);
        nextButton.setBounds(390, 280, 57, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASPIRE V5\\Documents\\PROYEK OOP\\Light-Wood-Background-Wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 3, 490, 380);

        setSize(new java.awt.Dimension(507, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bahan2textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bahan2textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bahan2textfieldActionPerformed

    private void tampilkanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanButtonActionPerformed
String bahan1=bahan1textfield.getText();
String bahan2=bahan2textfield.getText();
String bahan3=bahan3textfield.getText();
String resep;
String kode;

try{
        Class.forName("com.mysql.jdbc.Driver");
             Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/resep_makanan1","resep","0");
             Statement statement = connection.createStatement();
             String sql="select nama_resep from resep where bahan LIKE '%"+bahan1+"%' AND bahan LIKE '%"+bahan2+"%'"
                     + "AND bahan LIKE '%"+bahan3+"%'";
             ResultSet rs = statement.executeQuery(sql);
             while(rs.next()){
                 resep=(rs.getString("nama_resep"));
                 
                 
                 
                tampilTextArea.append(resep+" ,\n");
                                  
             }
             statement.close();
    }catch (Exception e){
            JOptionPane.showMessageDialog(null, "ada kesalahan \n"+e);
    }// TODO add your handling code here:
    }//GEN-LAST:event_tampilkanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masukanBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masukanBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masukanBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masukanBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masukanBahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bahan1textfield;
    private javax.swing.JTextField bahan2textfield;
    private javax.swing.JTextField bahan3textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextArea tampilTextArea;
    private javax.swing.JButton tampilkanButton;
    // End of variables declaration//GEN-END:variables
}
